apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
data:
  DB_HOST: "postgres-service"
  DB_NAME: "appdb"
  ENV: "prod"
  REDIS_HOST: "redis-service"
  MINIO_ENDPOINT: "minio-server:9000"
  MINIO_BUCKET: "assets"
