apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
data:
  DB_HOST: "postgres-service"
  DB_NAME: "appdb"
  ENV: "dev"
  REDIS_HOST: "" # No se usa en dev
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_BUCKET: "assets"
