apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: app-image:v1
          ports:
            - containerPort: 5000
          # Entrypoint: ejecuta el upload antes de arrancar la app para ver logs y asegurar disponibilidad
          command: ["/bin/sh", "-c"]
          args:
            - |
              python /app/upload_assets.py && \
              gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 60 app:app
          imagePullPolicy: Never
          env:
          # Entorno en el que nos encontramos
          - name: ENV
            valueFrom:
              configMapKeyRef:
                name: infra-config
                key: ENV
          # Conexión a Postgres
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: infra-config
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: infra-config
                key: DB_NAME
          # Credenciales Postges
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: infra-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: infra-secrets
                key: DB_PASSWORD
          # Conexión a Redis
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: infra-config
                key: REDIS_HOST
          # Configuración MinIO
          - name: MINIO_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: infra-config
                key: MINIO_ENDPOINT
          - name: MINIO_BUCKET
            valueFrom:
              configMapKeyRef:
                name: infra-config
                key: MINIO_BUCKET
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: infra-secrets
                key: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: infra-secrets
                key: MINIO_SECRET_KEY
